In [ ]:
#Enumerate
xyz = ['x','y','z']

for i, value in enumerate(xyz):
  print(f"{i}: {value}")

In [ ]:
#Zip
list1 = ['a','b','c','d','e','f','g']
list2 = [10, 20, 30, 40, 50]
list3 = ['#123', '#456', '#789']

for par in zip(list1, list2, list3):
  print(par)

In [ ]:
#Range
numeros = [45, 34, 1, 2, 3]
numeros_2 = numeros[3:5]
print(numeros_2)

In [ ]:
#Range

print(list(range(4)))

print(list(range(1,5)))

print(list(range(1, 10, 2)))

print(list(range(-5)))

print(list(range(10, 5)))

print(list(range(1, 10, -2)))

In [40]:
# Exercícios com enumerate

# 1
chico_altura = 1.50
ze_altura = 1.10
chico_crescimento = 0.02
ze_crescimento = 0.03

anos = range(1, 100)

for ano, (chico, ze) in enumerate(zip(
    [chico_altura + chico_crescimento * i for i in anos],
    [ze_altura + ze_crescimento * i for i in anos]), 1):
    if ze > chico:
       print(f'Após {ano} ano(s), Zé será maior que Chico!')
        break
# 2

transacoes = [49, 40, -32, 11, 18, 9, -32, 1, -8, -34,
-39, -30, -33, 38, 36, 35, -46, 16, 43, -23,
44, -22, 50, -50, 46, 24, 49, -42, 12, -1]

for dia, valor in enumerate(transacoes, start = 1):
  print (f'No dia {dia} transação de R$ {valor}')

No dia 1 transação de R$ 49
No dia 2 transação de R$ 40
No dia 3 transação de R$ -32
No dia 4 transação de R$ 11
No dia 5 transação de R$ 18
No dia 6 transação de R$ 9
No dia 7 transação de R$ -32
No dia 8 transação de R$ 1
No dia 9 transação de R$ -8
No dia 10 transação de R$ -34
No dia 11 transação de R$ -39
No dia 12 transação de R$ -30
No dia 13 transação de R$ -33
No dia 14 transação de R$ 38
No dia 15 transação de R$ 36
No dia 16 transação de R$ 35
No dia 17 transação de R$ -46
No dia 18 transação de R$ 16
No dia 19 transação de R$ 43
No dia 20 transação de R$ -23
No dia 21 transação de R$ 44
No dia 22 transação de R$ -22
No dia 23 transação de R$ 50
No dia 24 transação de R$ -50
No dia 25 transação de R$ 46
No dia 26 transação de R$ 24
No dia 27 transação de R$ 49
No dia 28 transação de R$ -42
No dia 29 transação de R$ 12
No dia 30 transação de R$ -1